### ISSUE TITLE
Issue with 2D scalar field - offset 

### ISSUE THREAD

**Issue by WJPeace1** [uob-positron-imaging-centre/up4#29]
![new_667_200mm_vel_cs_xy_plane](https://user-images.githubusercontent.com/71898186/220365340-34d61205-11cd-4329-b310-e6e8bab1fa74.png)
![667_200mm_vel_cs_xy_plane](https://user-images.githubusercontent.com/71898186/220365345-74925648-95ce-420a-930d-e20702b8e1e2.png)

The latest update of the software has had an issue where the scalar fields have become offset. Image 1 is a new plot, image 2 is the old plot - both of scalar velocity in the XY plane. The data seems to be offset in both of the axes. Furthermore, the data seems to show different colours at some cells - perhaps indicating a change in the way velocity has been calculated?

**Comment by dwerner95** [comment]
can you attach the code that you used to produce that plot please?

**Comment by WJPeace1** [comment]
> can you attach the code that you used to produce that plot please?

`grid = up4.Grid.cartesian3d_from_data(data, cells = [25 ,25,25])

field = data.velocityfield(grid)

xpos,ypos,zpos = field.cell_positions()
fig.add_trace(go.Heatmap(z = avg_field_ax0))

fig.update_layout(
    xaxis = dict(
        tickmode = 'array',
        tickvals = [0,int(cx/4),int(cx/2),int((3*cx)/4),int(cx-1)],
        ticktext = ["<b> -1 </b>", "<b> -0.5 </b>","<b> 0 </b> ", "<b> 0.5 </b> ","<b> 1 </b>"],
    ),
    yaxis = dict(
        tickmode = 'array',
        tickvals = [0,int(cx/4),int(cx/2),int((3*cx)/4),int(cx-1)],
        ticktext = ["<b> 0 </b>", "<b> 0.25 </b>","<b> 0.5 </b> ", "<b> 0.75 </b> ","<b> 1 </b>"],
    ),
)

fig.show()`

**Comment by dwerner95** [comment]
Yes i see, there is an issue with commit 2325961. The [`cell_id`](https://github.com/uob-positron-imaging-centre/up4/blob/uPPPP/src/grid/cartesian_grid.rs#:~:text=fn%20cell_id(%26self%2C%20pos%3A%20Position)%20%2D%3E%20CellId) function in the cartesian grid is wrong. I am working on this. Should be a quick fix.

**Comment by dwerner95** [comment]
Commit 95cb65f should have fixed it. can you try and tell me?
