### ISSUE TITLE
Velocity scalar and velocity vector fields are flipped

### ISSUE THREAD

**Issue by WJPeace1** [uob-positron-imaging-centre/up4#33]
![1 6VVM_VelVectorXZ_Slice](https://github.com/uob-positron-imaging-centre/up4/assets/71898186/a48d353b-310a-4c3e-8748-a6f13796bff0)
![1 6VVM_VelScalarXZ_Slice](https://github.com/uob-positron-imaging-centre/up4/assets/71898186/639fa891-ad35-469b-8104-7e6a16d89931)

The attached files show a velocity vector and a velocity scalar field in the same plane at the same location. As seen by the heatmap, the velocities are flipped about the centre of the image. This is true for all data in any axis view.

**Comment by DanW97** [comment]
Oops!

I will investigate.

**Comment by DanW97** [comment]
Hi @WJPeace1 can you share the script you were using for the plots?

**Comment by WJPeace1** [comment]
Hi @DanW97, here you go!

`# # # Velocity Fields # # #
from math import inf
from re import template
import numpy as np
import plotly as p
import plotly.express as pexp
import plotly.graph_objects as go
import up4
from collections import defaultdict

# # # Import data # # #
hdf_name = '16_190_trajectories.hdf5'

# # # Extract values for plots and tip speed calculation # # #
filename_final = hdf_name.split(".hdf5")[0]
variables = filename_final.split("_")

if int(variables[0]) > 0:
    vvm = str(int(variables[0])/10) + str("VVM")
else:
    vvm = str("Ungassed")
print(vvm)

speed = int(variables[1])
speed_rpm = str(int(variables[1])) + str("RPM")
statement = str(vvm) + str(" - ") + str(speed_rpm)
tip_speed = (2 * np.pi * speed * (1/60) * 0.033)
save_statement = str(speed_rpm) + str("_") + str(vvm)

# # # Data Load-In # # #
data = up4.Data(hdf_name)

# # # Dimension Statistics # # # 
dim = data.dimensions()
xmin = dim['xmin']
xmax = dim['xmax']
ymin = dim['ymin']
ymax = dim['ymax']
zmin = dim['zmin']
zmax = dim['zmax']
xmed = (xmin + xmax) * 0.5 # midpoint in x-axis
ymed = (ymin + ymax) * 0.5 # midpoint in y-axis
zimpeller = zmin + ((zmax - zmin)/3) # impeller level in the tank

# # # Forming a Grid # # #
cx = 25
cy = cx
cz = cx

grid = up4.Grid.cartesian3d_from_data(data, cells = [cx,cy,cz]) # cartesian co-ordinates
# grid = up4.Grid.cylindrical3d_from_data(data, cells = [cx,cy,cz]) # cylinderical co-ordinates
field = data.velocityfield(grid)
xpos,ypos,zpos = field.cell_positions()

# # # CENTRE SLICES # # #

# YMed Slice
vel_slice_ymed = np.rot90(field.slice_pos(axis = 1, position = ymed),3)
fig = go.Figure()
fig.add_trace(go.Heatmap(z = vel_slice_ymed, zmin = 0))
fig.update_layout(
    title = str(f"<b>{statement}" + ": Central Slice Velocity Field: XZ Plane </b>"),
    title_x = 0.5,
    width = 1000,
    height = 1000,
    xaxis_title = "<b> r/R </b>",
    yaxis_title = "<b> z/H </b>",
    xaxis = dict(
        tickmode = 'array',
        tickvals = [0,int(cx/4),int(cx/2),int((3*cx)/4),int(cx-1)],
        ticktext = ["<b> -1 </b>", "<b> -0.5 </b>","<b> 0 </b> ", "<b> 0.5 </b> ","<b> 1 </b>"],
    ),
    yaxis = dict(
        tickmode = 'array',
        tickvals = [0,int(cx/4),int(cx/2),int((3*cx)/4),int(cx-1)],
        ticktext = ["<b> 0 </b>", "<b> 0.25 </b>","<b> 0.5 </b> ", "<b> 0.75 </b> ","<b> 1 </b>"],
    ),
    template = "plotly_white",
    font = dict(
        family = "Arial",
        size = 20,
        color = "black",
    )
)

fig.show()
#img_title = str(save_statement + "_VelScalarXZ_Slice.png")
#fig.write_image(img_title)
#del img_title

`
